server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD.key}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/profile2web
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD.key}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

contact:
  to: rmkaheto4java@gmail.com

recaptcha:
  secretKey: ${GOOGLE_RECAPTCHA_SECRET.key}
  verifyUrl: https://www.google.com/recaptcha/api/siteverify

app:
  backend-base-url: http://localhost:8090

jwt:
  secret: ${ENCRYPTION_SECRET_KEY}  # Load secret from an external file
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds